## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mount Isa,AU,-20.7333,139.5000,82.17,17,7,5.75,clear sky
1,1,Kahului,US,20.8947,-156.4700,80.62,71,20,23.02,few clouds
2,2,Hoa Binh,VN,20.8133,105.3383,87.93,69,88,3.76,light rain
3,3,Hermanus,ZA,-34.4187,19.2345,57.51,78,94,12.55,overcast clouds
4,4,Chuy,UY,-33.6971,-53.4616,45.05,79,0,6.51,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       
                                       (city_data_df["Max Temp"] >= min_temp)]

preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mount Isa,AU,-20.7333,139.5000,82.17,17,7,5.75,clear sky
1,1,Kahului,US,20.8947,-156.4700,80.62,71,20,23.02,few clouds
2,2,Hoa Binh,VN,20.8133,105.3383,87.93,69,88,3.76,light rain
5,5,Sao Joao Da Barra,BR,-21.6403,-41.0511,70.92,92,62,11.83,broken clouds
6,6,Coahuayana,MX,18.7333,-103.6833,78.84,84,92,1.83,overcast clouds
9,9,Ixtapa,MX,20.7000,-105.2000,81.23,83,40,3.44,scattered clouds
10,10,Vaini,TO,-21.2000,-175.2000,78.96,94,75,9.22,broken clouds
12,12,Delray Beach,US,26.4615,-80.0728,86.00,83,0,10.36,clear sky
14,14,Soto La Marina,MX,23.7667,-98.2167,77.77,84,59,6.53,broken clouds
15,15,Palmer,US,42.1584,-72.3287,75.06,68,100,6.91,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mount Isa,AU,-20.7333,139.5000,82.17,17,7,5.75,clear sky
1,1,Kahului,US,20.8947,-156.4700,80.62,71,20,23.02,few clouds
2,2,Hoa Binh,VN,20.8133,105.3383,87.93,69,88,3.76,light rain
5,5,Sao Joao Da Barra,BR,-21.6403,-41.0511,70.92,92,62,11.83,broken clouds
6,6,Coahuayana,MX,18.7333,-103.6833,78.84,84,92,1.83,overcast clouds
9,9,Ixtapa,MX,20.7000,-105.2000,81.23,83,40,3.44,scattered clouds
10,10,Vaini,TO,-21.2000,-175.2000,78.96,94,75,9.22,broken clouds
12,12,Delray Beach,US,26.4615,-80.0728,86.00,83,0,10.36,clear sky
14,14,Soto La Marina,MX,23.7667,-98.2167,77.77,84,59,6.53,broken clouds
15,15,Palmer,US,42.1584,-72.3287,75.06,68,100,6.91,overcast clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mount Isa,AU,82.17,clear sky,-20.7333,139.5000,
1,Kahului,US,80.62,few clouds,20.8947,-156.4700,
2,Hoa Binh,VN,87.93,light rain,20.8133,105.3383,
5,Sao Joao Da Barra,BR,70.92,broken clouds,-21.6403,-41.0511,
6,Coahuayana,MX,78.84,overcast clouds,18.7333,-103.6833,
9,Ixtapa,MX,81.23,scattered clouds,20.7000,-105.2000,
10,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,
12,Delray Beach,US,86.00,clear sky,26.4615,-80.0728,
14,Soto La Marina,MX,77.77,broken clouds,23.7667,-98.2167,
15,Palmer,US,75.06,overcast clouds,42.1584,-72.3287,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():


    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try: 
        
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError): 
        
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mount Isa,AU,82.17,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
1,Kahului,US,80.62,few clouds,20.8947,-156.4700,Maui Seaside Hotel
2,Hoa Binh,VN,87.93,light rain,20.8133,105.3383,Hoa Dao Hotel
5,Sao Joao Da Barra,BR,70.92,broken clouds,-21.6403,-41.0511,Pousada Porto De Canoas
6,Coahuayana,MX,78.84,overcast clouds,18.7333,-103.6833,El rranchito michuacan de ocampos
9,Ixtapa,MX,81.23,scattered clouds,20.7000,-105.2000,hotel la terminal
10,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
12,Delray Beach,US,86.00,clear sky,26.4615,-80.0728,Opal Grand Resort
14,Soto La Marina,MX,77.77,broken clouds,23.7667,-98.2167,Hotel Chicago
15,Palmer,US,75.06,overcast clouds,42.1584,-72.3287,Wedgewood Motel

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))